# New York City Taxi Trip Duration 02 - Machine Learning

###   
### 목표 : 데이터를 가지고 택시 주행거리 예측 모델 구축
###   
###   

## 1. 데이터 전처리 

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

train = pd.read_csv("train.csv", parse_dates = ['pickup_datetime', 'dropoff_datetime'])
test = pd.read_csv("test.csv", parse_dates = ['pickup_datetime'])
submission = pd.read_csv("sample_submission.csv")

train['pickup_year'] = train['pickup_datetime'].dt.year  
train['pickup_month'] = train['pickup_datetime'].dt.month
train['pickup_day'] = train['pickup_datetime'].dt.day
train['pickup_hour'] = train['pickup_datetime'].dt.hour
train['pickup_minute'] = train['pickup_datetime'].dt.minute
train['pickup_second'] = train['pickup_datetime'].dt.second
train["pickup_dayofweek"] = train["pickup_datetime"].dt.dayofweek 

test['pickup_year'] = test['pickup_datetime'].dt.year  
test['pickup_month'] = test['pickup_datetime'].dt.month
test['pickup_day'] = test['pickup_datetime'].dt.day
test['pickup_hour'] = test['pickup_datetime'].dt.hour
test['pickup_minute'] = test['pickup_datetime'].dt.minute
test['pickup_second'] = test['pickup_datetime'].dt.second
test["pickup_dayofweek"] = test["pickup_datetime"].dt.dayofweek 


train['store_and_fwd_flag_Y'] = train['store_and_fwd_flag'] == 'Y'
train['store_and_fwd_flag_N'] = train['store_and_fwd_flag'] == 'N'

test['store_and_fwd_flag_Y'] = test['store_and_fwd_flag'] == 'Y'
test['store_and_fwd_flag_N'] = test['store_and_fwd_flag'] == 'N'


train['vendor_1'] = train['vendor_id'] == 1
train['vendor_2'] = train['vendor_id'] == 2

test['vendor_1'] = test['vendor_id'] == 1
test['vendor_2'] = test['vendor_id'] == 2


train['passenger_0'] = train['passenger_count'] == 0
train['passenger_1'] = train['passenger_count'] == 1
train['passenger_2'] = train['passenger_count'] == 2
train['passenger_3'] = train['passenger_count'] == 3
train['passenger_4'] = train['passenger_count'] == 4
train['passenger_5'] = train['passenger_count'] == 5
train['passenger_6'] = train['passenger_count'] == 6
train['passenger_7'] = train['passenger_count'] == 7
train['passenger_8'] = train['passenger_count'] == 8
train['passenger_9'] = train['passenger_count'] == 9

test['passenger_0'] = test['passenger_count'] == 0
test['passenger_1'] = test['passenger_count'] == 1
test['passenger_2'] = test['passenger_count'] == 2
test['passenger_3'] = test['passenger_count'] == 3
test['passenger_4'] = test['passenger_count'] == 4
test['passenger_5'] = test['passenger_count'] == 5
test['passenger_6'] = test['passenger_count'] == 6
test['passenger_7'] = test['passenger_count'] == 7
test['passenger_8'] = test['passenger_count'] == 8
test['passenger_9'] = test['passenger_count'] == 9

print("완료!")

완료!


####     
####  

## 2. 변수 선택 및 데이터 조정

### 1) 변수 선택

In [2]:
print(train.shape)
train.columns

(1458644, 32)


Index(['id', 'vendor_id', 'pickup_datetime', 'dropoff_datetime',
       'passenger_count', 'pickup_longitude', 'pickup_latitude',
       'dropoff_longitude', 'dropoff_latitude', 'store_and_fwd_flag',
       'trip_duration', 'pickup_year', 'pickup_month', 'pickup_day',
       'pickup_hour', 'pickup_minute', 'pickup_second', 'pickup_dayofweek',
       'store_and_fwd_flag_Y', 'store_and_fwd_flag_N', 'vendor_1', 'vendor_2',
       'passenger_0', 'passenger_1', 'passenger_2', 'passenger_3',
       'passenger_4', 'passenger_5', 'passenger_6', 'passenger_7',
       'passenger_8', 'passenger_9'],
      dtype='object')

In [3]:
print(test.shape)
test.columns

(625134, 30)


Index(['id', 'vendor_id', 'pickup_datetime', 'passenger_count',
       'pickup_longitude', 'pickup_latitude', 'dropoff_longitude',
       'dropoff_latitude', 'store_and_fwd_flag', 'pickup_year', 'pickup_month',
       'pickup_day', 'pickup_hour', 'pickup_minute', 'pickup_second',
       'pickup_dayofweek', 'store_and_fwd_flag_Y', 'store_and_fwd_flag_N',
       'vendor_1', 'vendor_2', 'passenger_0', 'passenger_1', 'passenger_2',
       'passenger_3', 'passenger_4', 'passenger_5', 'passenger_6',
       'passenger_7', 'passenger_8', 'passenger_9'],
      dtype='object')

#### 모델링에 필요한 변수들 선택

In [ ]:
feature_names = [ 'pickup_longitude', 'pickup_latitude',  
                  'store_and_fwd_flag_Y', 'store_and_fwd_flag_N',
                  'pickup_year', 'pickup_month', 'pickup_day',
                  'pickup_hour', 'pickup_minute', 'pickup_second', 'pickup_dayofweek',
                  'vendor_id', 'vendor_1', 'vendor_2',
                  'passenger_count', 'passenger_0', 'passenger_1', 'passenger_2', 'passenger_3',
                  'passenger_4', 'passenger_5', 'passenger_6', 'passenger_7', 'passenger_8', 
                  'passenger_9']

#### 'id'는 단순 구분을 위한 값이고,  'pickup_datetime'의 경우 날짜형태라 제외
#### 'dropoff_longitude', 'dropoff_latitude', 'dropoff_datetime'는 test 데이터에 없음
#### 'store_and_fwd_flag'의 경우 Y와 N이 문자열이기 때문에 계산을 못함. 원핫인코딩만 사용
#### 'trip_duration'은 목표값이니 제외

In [ ]:
basic_features : 모든 변수 포함
feature_names =['pickup_longitude', 'pickup_latitude',  
                  'store_and_fwd_flag_Y', 'store_and_fwd_flag_N',
                  'pickup_year', 'pickup_month', 'pickup_day',
                  'pickup_hour', 'pickup_minute', 'pickup_second', 'pickup_dayofweek',
                  'vendor_id', 'vendor_1', 'vendor_2',
                  'passenger_count', 'passenger_0', 'passenger_1', 'passenger_2', 'passenger_3',
                  'passenger_4', 'passenger_5', 'passenger_6', 'passenger_7', 'passenger_8', 
                  'passenger_9']

feautres_1 : vendor_id와 passenger_count의 경우 원핫인코딩 제외
feautres_1 = ['pickup_longitude', 'pickup_latitude',  
              'store_and_fwd_flag_Y', 'store_and_fwd_flag_N',
              'pickup_year', 'pickup_month', 'pickup_day',
              'pickup_hour', 'pickup_minute', 'pickup_second', 'pickup_dayofweek',
              'vendor_id',
              'passenger_count']
    
feautres_2 : vendor_id와 passenger_count의 경우 원핫인코딩만 사용
feautres_2 = ['pickup_longitude', 'pickup_latitude',  
              'store_and_fwd_flag_Y', 'store_and_fwd_flag_N',
              'pickup_year', 'pickup_month', 'pickup_day',
              'pickup_hour', 'pickup_minute', 'pickup_second', 'pickup_dayofweek',
              'vendor_1', 'vendor_2',
              'passenger_0', 'passenger_1', 'passenger_2', 'passenger_3',
              'passenger_4', 'passenger_5', 'passenger_6', 'passenger_7', 'passenger_8', 
              'passenger_9']
    
feautres_3 :  초 제외 /vendor_id와 passenger_count의 경우 원핫인코딩만 사용
feautres_3 = ['pickup_longitude', 'pickup_latitude',  
              'store_and_fwd_flag_Y', 'store_and_fwd_flag_N',
              'pickup_year', 'pickup_month', 'pickup_day',
              'pickup_hour', 'pickup_minute', 'pickup_dayofweek',
              'vendor_1', 'vendor_2',
              'passenger_0', 'passenger_1', 'passenger_2', 'passenger_3',
              'passenger_4', 'passenger_5', 'passenger_6', 'passenger_7', 'passenger_8', 
              'passenger_9']

feautres_4 :  날짜 제외 / vendor_id와 passenger_count의 경우 원핫인코딩만 사용
feautres_4 = ['pickup_longitude', 'pickup_latitude',  
              'store_and_fwd_flag_Y', 'store_and_fwd_flag_N',
              'pickup_hour', 'pickup_minute', 'pickup_dayofweek',
              'vendor_1', 'vendor_2',
              'passenger_0', 'passenger_1', 'passenger_2', 'passenger_3',
              'passenger_4', 'passenger_5', 'passenger_6', 'passenger_7', 'passenger_8', 
              'passenger_9']

In [2]:
feature_names =['pickup_longitude', 'pickup_latitude',  
                  'store_and_fwd_flag_Y', 'store_and_fwd_flag_N',
                  'pickup_year', 'pickup_month', 'pickup_day',
                  'pickup_hour', 'pickup_minute', 'pickup_second', 'pickup_dayofweek',
                  'vendor_id', 'vendor_1', 'vendor_2',
                  'passenger_count', 'passenger_0', 'passenger_1', 'passenger_2', 'passenger_3',
                  'passenger_4', 'passenger_5', 'passenger_6', 'passenger_7', 'passenger_8', 
                  'passenger_9']  # basic

# RF

In [2]:
feature_names = ['pickup_longitude', 'pickup_latitude',  
              'store_and_fwd_flag_Y', 'store_and_fwd_flag_N',
              'pickup_hour', 'pickup_minute', 'pickup_dayofweek',
              'vendor_1', 'vendor_2',
              'passenger_0', 'passenger_1', 'passenger_2', 'passenger_3',
              'passenger_4', 'passenger_5', 'passenger_6', 'passenger_7', 'passenger_8', 
              'passenger_9']

### 2) 데이터 조정

In [3]:
x_train = train[feature_names]
print(x_train.shape)
x_train.head()

(1458644, 25)


pickup_longitude  pickup_latitude  store_and_fwd_flag_Y  \
0        -73.982155        40.767937                 False   
1        -73.980415        40.738564                 False   
2        -73.979027        40.763939                 False   
3        -74.010040        40.719971                 False   
4        -73.973053        40.793209                 False   

   store_and_fwd_flag_N  pickup_year  pickup_month  pickup_day  pickup_hour  \
0                  True         2016             3          14           17   
1                  True         2016             6          12            0   
2                  True         2016             1          19           11   
3                  True         2016             4           6           19   
4                  True         2016             3          26           13   

   pickup_minute  pickup_second     ...       passenger_0  passenger_1  \
0             24             55     ...             False         True   
1             43             35     ...             False         True   
2             35             24     ...             False         True   
3             32             31     ...             False         True   
4             30             55     ...             False         True   

   passenger_2  passenger_3  passenger_4  passenger_5  passenger_6  \
0        False        False        False        False        False   
1        False        False        False        False        False   
2        False        False        False        False        False   
3        False        False        False        False        False   
4        False        False        False        False        False   

   passenger_7  passenger_8  passenger_9  
0        False        False        False  
1        False        False        False  
2        False        False        False  
3        False        False        False  
4        False        False        False  

[5 rows x 25 columns]

In [4]:
x_test = test[feature_names]
print(x_test.shape)
x_test.head()

(625134, 25)


pickup_longitude  pickup_latitude  store_and_fwd_flag_Y  \
0        -73.988129        40.732029                 False   
1        -73.964203        40.679993                 False   
2        -73.997437        40.737583                 False   
3        -73.956070        40.771900                 False   
4        -73.970215        40.761475                 False   

   store_and_fwd_flag_N  pickup_year  pickup_month  pickup_day  pickup_hour  \
0                  True         2016             6          30           23   
1                  True         2016             6          30           23   
2                  True         2016             6          30           23   
3                  True         2016             6          30           23   
4                  True         2016             6          30           23   

   pickup_minute  pickup_second     ...       passenger_0  passenger_1  \
0             59             58     ...             False         True   
1             59             53     ...             False         True   
2             59             47     ...             False         True   
3             59             41     ...             False         True   
4             59             33     ...             False         True   

   passenger_2  passenger_3  passenger_4  passenger_5  passenger_6  \
0        False        False        False        False        False   
1        False        False        False        False        False   
2        False        False        False        False        False   
3        False        False        False        False        False   
4        False        False        False        False        False   

   passenger_7  passenger_8  passenger_9  
0        False        False        False  
1        False        False        False  
2        False        False        False  
3        False        False        False  
4        False        False        False  

[5 rows x 25 columns]

In [5]:
label_name = "trip_duration"

y_train = train[label_name]
print(y_train.shape)
y_train.head()

(1458644,)


0     455
1     663
2    2124
3     429
4     435
Name: trip_duration, dtype: int64

In [6]:
y_train = np.log1p(y_train)
y_train.head()

0    6.122493
1    6.498282
2    7.661527
3    6.063785
4    6.077642
Name: trip_duration, dtype: float64

####   
####    

## 3. Linear Regression

#### 기본

In [8]:
from sklearn import linear_model

LR_model = linear_model.LinearRegression()
LR_model.fit(x_train, y_train)

predictions = LR_model.predict(x_test)
predictions = np.expm1(predictions)
predictions[0:10]

array([722.4012868 , 897.43401767, 699.8967529 , 669.96028581,
       665.1235513 , 675.24198506, 707.16894828, 828.53860806,
       787.15288412, 694.66236882])

#### hyperparameters 조정

In [2]:
from sklearn import linear_model
LR_model = linear_model.LinearRegression()
LR_model

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [16]:
from sklearn import linear_model
LR_model = linear_model.LinearRegression(fit_intercept=False)
LR_model.fit(x_train, y_train)

predictions = LR_model.predict(x_test)
predictions = np.expm1(predictions)
predictions[0:10]

array([722.40128681, 897.43401768, 699.89675291, 669.96028582,
       665.12355131, 675.24198507, 707.16894829, 828.53860807,
       787.15288413, 694.66236883])

#### 제출

In [17]:
submission['trip_duration'] = predictions
submission.to_csv('LR8.csv', index = False)

#### 결과보고서

In [ ]:
LR / basic_features : 0.77677
LR / features_1     : 0.77714
LR / features_2     : 0.77677
LR / features_3     : 0.77677
LR / features_4     : 0.77762
    
LR / basic_features / normalize = True : 0.95757
LR / basic_features / normalize=True  fit_intercept=False : 0.77677
LR / basic_features / fit_intercept=False : 0.77677    

####  
####  

## 4. Decision Tree Regressor

#### 기본

In [9]:
from sklearn.tree import DecisionTreeRegressor

DT_model = DecisionTreeRegressor()
DT_model.fit(x_train, y_train)

predictions = DT_model.predict(x_test)
predictions = np.expm1(predictions)
predictions[0:10]

array([ 452.,  279., 2214., 1025.,  249., 1464.,  760.,    3.,  184.,
        222.])

#### hyperparameters 조정

In [18]:
from sklearn.tree import DecisionTreeRegressor

DT_model = DecisionTreeRegressor()
DT_model

DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
           max_leaf_nodes=None, min_impurity_split=1e-07,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, presort=False, random_state=None,
           splitter='best')

In [ ]:
from sklearn.tree import DecisionTreeRegressor

DT_model = DecisionTreeRegressor(criterion='mae',
                                 max_depth = 10, random_state = 50)     # 12시 35분 시작
DT_model.fit(x_train, y_train)

predictions = DT_model.predict(x_test)
predictions = np.expm1(predictions)
predictions[0:10]

#### 제출

In [37]:
submission['trip_duration'] = predictions
submission.to_csv('DC19.csv', index = False)

#### 결과보고서 

In [ ]:
DT / basic_features : 1.07356
DT / features_1     : 1.07007
DT / features_2     : 1.07381
DT / features_3     : 1.07070
DT / features_4     : 1.06416
    
DT / basic_features / max_depth = 12 random_state = 50 : 0.74603
DT / basic_features / max_depth = 10 random_state = 50 : 0.74505
DT / basic_features / max_depth = 8 random_state = 50 :  0.74690
DT / basic_features / max_depth = 9 random_state = 50 :  0.74551

DT / features_4  / max_depth = 10 random_state = 50 : 0.74460
DT / features_4  / max_depth = 10 random_state = 50 max_features = 'auto' :  0.74460
DT / features_4  / max_depth = 10 random_state = 50 max_features = 'sqrt' :  0.75377
DT / features_4  / max_depth = 10 random_state = 50 max_features = 'log2' :  0.75377
    
DT / features_4  / max_depth = 10 random_state = 50 : 0.74460 criterion='friedman_mse'  : 0.75377   
DT / features_4  / max_depth = 10 random_state = 50 : 0.74460 criterion='mae'  : 너무 오래걸려 실패

####   
####   

## 5. Random Forest Regressor

#### 기본

In [11]:
from sklearn.ensemble import RandomForestRegressor

RF_model = RandomForestRegressor()
RF_model.fit(x_train, y_train)

predictions = RF_model.predict(x_test)
predictions = np.expm1(predictions)
predictions[0:10]

array([ 493.97920857,  471.46022727, 1365.54733309, 1155.00641377,
        720.39310441,  924.81350014,  808.66244501,  349.61084641,
        638.72083385,  700.85066106])

#### hyperparameters 조정

In [7]:
from sklearn.ensemble import RandomForestRegressor

RF_model = RandomForestRegressor()
RF_model

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_split=1e-07, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           n_estimators=10, n_jobs=1, oob_score=False, random_state=None,
           verbose=0, warm_start=False)

In [7]:
import time
start = time.time()

from sklearn.ensemble import RandomForestRegressor

RF_model = RandomForestRegressor(n_estimators = 200, random_state =  50)
RF_model.fit(x_train, y_train)

predictions = RF_model.predict(x_test)
predictions = np.expm1(predictions)


print('Running Time : %.02f초' % (time.time() - start))
predictions[0:10]

Running Time : 3384.42초


array([601.4796587 , 673.67965576, 683.28955431, 607.84289472,
       611.37008858, 619.70124686, 514.59997453, 801.67211648,
       799.76207967, 535.73566747])

#### 제출

In [8]:
submission['trip_duration'] = predictions
submission.to_csv('RF8.csv', index = False)

#### 결과보고서

In [ ]:
RF / basic_features : 0.77799
RF / features_1     : 0.77918
RF / features_2     : 0.77863
RF / features_3     : 0.77942
RF / features_4     : 0.78734
    
RF / basic_features / random_state =  50 : 0.77764
RF / basic_features / n_estimators = 100 random_state =  50 : 0.74300
RF / basic_features / n_estimators = 200 random_state =  50 : 0.74087

####   
####   

## 6. Gradient Boost Regressor

#### 기본

In [12]:
from sklearn.ensemble import GradientBoostingRegressor

GB_model = GradientBoostingRegressor()
GB_model.fit(x_train, y_train)

predictions = GB_model.predict(x_test)
predcitions = np.expm1(predictions)
predictions[0:10]

array([6.47258578, 6.43930132, 6.47258578, 6.31684105, 6.39497078,
       6.50748801, 6.46367237, 6.80874323, 6.514045  , 6.50444774])

#### hyperparameters 조정

In [12]:
from sklearn.ensemble import GradientBoostingRegressor

GB_model = GradientBoostingRegressor()
GB_model

GradientBoostingRegressor(alpha=0.9, criterion='friedman_mse', init=None,
             learning_rate=0.1, loss='ls', max_depth=3, max_features=None,
             max_leaf_nodes=None, min_impurity_split=1e-07,
             min_samples_leaf=1, min_samples_split=2,
             min_weight_fraction_leaf=0.0, n_estimators=100,
             presort='auto', random_state=None, subsample=1.0, verbose=0,
             warm_start=False)

In [13]:
import time
start = time.time()

GB_model = GradientBoostingRegressor(n_estimators = 750, random_state =  50)
GB_model.fit(x_train, y_train)

predictions = GB_model.predict(x_test)
predcitions = np.expm1(predictions)
predictions[0:10]

print('Running Time : %.02f초' % (time.time() - start))

Running Time : 1637.80초


#### 제출

In [14]:
submission['trip_duration'] = predictions
submission.to_csv('GB3.csv', index = False)

#### 결과보고서

In [ ]:
GB / basic_features : 4.52659
GB / features_1     : 4.52659
    
GB / basic_features / n_estimators = 750 random_state =  50 : 4.52634

####   
####   

## 7. XGBoost Regressor 

In [13]:
import xgboost as xgb

XGB_model = xgb.XGBRegressor()
XGB_model.fit(x_train, y_train)

predictions = XGB_model.predict(x_test)
predictions = np.expm1(predictions)
predictions[0:10]

C:\Users\Jeong\Anaconda3\lib\site-packages\sklearn\cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


array([627.7671 , 596.0789 , 627.7671 , 539.74396, 578.3258 , 651.4362 ,
       621.8366 , 894.3545 , 659.97076, 649.33655], dtype=float32)

In [14]:
submission['trip_duration'] = predictions
submission.to_csv('XGB5.csv', index = False)

#### 결과보고서

In [ ]:
XGB / basic_features : 0.74462
XGB / features_1     : 0.74462
XGB / features_2     : 0.74448
XGB / features_3     : 0.74448
XGB / features_4     : 0.74536